---
- hosts: localhost
  become: true
  vars:
  - ssh_pub_key: "{{ lookup('file','/home/wakausr/.ssh/id_rsa.pub') }}"
  tasks:
  - name: mount the base media for rhel6
    mount:
      path: /media6
      src: "{{ iso_ver6 }}"
      fstype: iso9660
      backup: yes
      state: mounted
      boot: yes
    tags: mountiso

  - name: mount the base media for rhel7
    mount:
      path: /media7
      src: "{{ iso_ver7 }}"
      fstype: iso9660
      backup: yes
      state: mounted
      boot: yes
    tags: mountiso

  - name: embed key in client source file
    replace:
      path: ~/rpmbuild/SOURCES/wakapp-client-1.0/wakapp-client.c
      regexp: "sshpubkey"
      replace: "{{ ssh_pub_key }}"
    tags: rebuildclient
 
  - name: Create scan_results & messages directory
    file:
      path: "/home/wakausr/{{ item }}"
      state: directory
      mode: 0755
      owner: wakausr
      group: wakausr
    with_items:
      - bin
      - scan_results
      - messages
      - logs
    tags: createdir

  - name: copy files to wakausr home directory
    copy:
      src: ../bin/
      dest: /home/wakausr/bin
      owner: wakausr
      group: wakausr
      mode: 0755
    tags: createdir

  - name: copy files to wakausr home directory
    copy:
      src: ../install/
      dest: /home/wakausr/install
      owner: wakausr
      group: wakausr
      mode: 0755
    tags: createdir
 
  - name: start & enable docker
    service:
      name: docker
      enabled: yes
      state: started
    tags: startdocker

  #- name: load docker images  
    #block:
    #- name: load redis image
      #docker_image:
        #name: redis 
        #load_path: ../images/redis.tar
    #- name: load nginx image
      #docker_image:
        #name: nginx
        #load_path: ../images/nginx.tar
    #- name: load rabbitmq image
      #docker_image:
        #name: rabbitmq
        #load_path: ../images/rabbitmq.tar
    #- name: load rhel-proxy7 image
      #docker_image:
        #name: rhel-proxy-7
        #load_path: ../images/rhel-proxy-7.tar
    #tags: containerimages

  - name: load docker images
    block:
    - name: load redis image
      docker_image:
        name: docker.io/nigelfoster/redis
        source: pull
    - name: load nginx image
      docker_image:
        name: docker.io/nigelfoster/nginx
        source: pull
    - name: load rabbitmq image
      docker_image:
        name: docker.io/nigelfoster/rabbitmq:3-management
        source: pull
    - name: load rhel-proxy7 image
      docker_image:
        name: docker.io/nigelfoster/rhel-proxy:7c
        source: pull
    tags: containerimages
 
  - name: create redis container
    docker_container:
      name: myredis
      image: redis
      state: started
      restart_policy: always
      ports: "6379:6379"
    tags: containers

  - name: create nginx containers
    docker_container:
      name: mynginx
      image: nginx
      state: started
      restart_policy: always
      ports: "8888:80"
      volumes:
      - /home/wakausr/install/default.conf:/etc/nginx/conf.d/default.conf:ro
      - /var/cache/yum/x86_64/7Server/stream7:/usr/share/nginx/html/stream7:ro
      - /var/cache/yum/x86_64/7Server/stream6:/usr/share/nginx/html/stream6:ro
      - /media7:/usr/share/nginx/html/media7:ro
      - /media6:/usr/share/nginx/html/media6:ro
    tags: containers

  - name: create rabbitmq containers
    docker_container:
      name: myrabbit
      image: rabbitmq:3-management
      state: started
      restart_policy: always
      ports: 
      - "5672:5672"
      - "15672:15672"
      env:
        hostname: rabbit-mq
    tags: containers 
  
  - name: firewall rules
    firewalld:
      port: "{{ item }}"
      immediate: yes
      state: enabled
      permanent: yes
    with_items:
    - 5672/tcp
    - 15672/tcp
    - 8888/tcp
    - 6379/tcp
    tags: parefeu  
